include $(CURDIR)/../../../GNUmakefile.whereis
include $(CURDIR)/../../../GNUmakefile.config.mine
include $(CURDIR)/../../../GNUmakefile.config

FILES=option int_option string_option config_manager

LIB=

CXXFLAGS+=-I.. -I../..

test:
	@true

include $(CURDIR)/../../../GNUmakefile.compile_cpp
