include $(CURDIR)/../../../GNUmakefile.whereis
include $(CURDIR)/../../../GNUmakefile.config.mine
include $(CURDIR)/../../../GNUmakefile.config

FILES=option int_option string_option config_manager bool_option \
      url_option rx_option quad_option sys_option syn_option

LIB=

CXXFLAGS+=-I.. -I../..

test:
	@true

include $(CURDIR)/../../../GNUmakefile.compile_cpp
