
FILES=libmuttng_mailbox_create libmuttng_signal libmuttng_url
LIB=
APPS=$(patsubst %,app_%,$(FILES))

include $(CURDIR)/../../GNUmakefile.whereis
include $(CURDIR)/../../GNUmakefile.config.mine
include $(CURDIR)/../../GNUmakefile.config

CXXFLAGS+=-I../../src -I../../src/libmuttng

include $(CURDIR)/../../GNUmakefile.compile_cpp

test: $(OBJS) $(APPS)

app_%: %.o
	$(CXX) -o $@ $^ $(LDFLAGS) ./../../src/libmuttng/libmuttng.a ./../../src/core/libcore.a

extraclean:
	rm -rf $(OBJS) $(APPS)
