# vim:ft=make

CCSTYLE?=gcc

ifeq ($(CCSTYLE),gcc)
CC?=$(call whereis,gcc,)
CXX?=$(call whereis,g++,)
AR?=$(call whereis,ar,)
RANLIB?=$(call whereis,ranlib,)
CFLAGS+=-Wall -Os -pipe -W -Wall -Wmissing-prototypes -Wmissing-declarations -Wparentheses -Wpointer-arith -Wredundant-decls -Wuninitialized -Wunused -Wno-format -Werror
CXXFLAGS+=-Wall -Os -pipe -W -Wall -Wparentheses -Wpointer-arith -Wredundant-decls -Wuninitialized -Wunused -Wno-format -Werror
DEPFLAG=-M
endif # CCSTYLE == gcc

ifeq ($(CCSTYLE),suncc)
CC?=$(call whereis,cc,)
CXX?=$(call whereis,cpp,)
AR?=$(call whereis,ar,)
RANLIB?=$(call whereis,ranlib,)
CFLAGS+=-Os -errwarn=%all -v
CXXFLAGS+=$(CFLAGS)
DEPFLAG=-xM
endif

ifneq ($(wildcard $(CURDIR)/.depend),)
include $(CURDIR)/.depend
else
#$(warning "Run 'make depend' first...")
endif

ifeq ($(DEBUG),1)
CFLAGS+=-g
CXXFLAGS+=-g
LDFLAGS+=-g
endif

MYOS=$(strip $(shell uname -s | tr 'a-z' 'A-Z' | sed 's/_.*$$//'))

CFLAGS+=-D$(MYOS)
CXXFLAGS+=-D$(MYOS)

UNITPPDIR?=/usr
CXXFLAGS+=-I$(UNITPPDIR)/include
CFLAGS+=-I$(UNITPPDIR)/include
LDFLAGS+=-L$(UNITPPDIR)/lib
