FILES=mailbox remote_mailbox imap_mailbox nntp_mailbox pop3_mailbox local_mailbox
LIB=

include $(CURDIR)/../../../GNUmakefile.config.default

CXXFLAGS+=-I.. -I../..

include $(CURDIR)/../../../GNUmakefile.compile_cpp
