FILES=crypto classic_crypto classic_pgp classic_smime crypto_gpgme
LIB=

include $(CURDIR)/../../../GNUmakefile.config.default

CXXFLAGS+=-I.. -I../..

include $(CURDIR)/../../../GNUmakefile.compile_cpp
